name: Deploy to Dokploy

on:
  push:
    branches:
      - main

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dokploy Rebuild
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: push" \
            -d '{"ref": "${{ github.ref }}", "repository": {"full_name": "${{ github.repository }}"}}' \
            "https://docker.semantier.com/api/deploy/compose/vccAIbGloP4TA6s1dxgQ2"           
